/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mob_jlogstash_InodeUtil */

#ifndef _Included_com_mob_jlogstash_InodeUtil
#define _Included_com_mob_jlogstash_InodeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mob_jlogstash_InodeUtil
 * Method:    getInode
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_mob_jlogstash_InodeUtil_getInode
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
